version: '3.8'
services:

  db:
    image: postgres:14.1-alpine3.15
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - '5432:5432'
    networks:
      - main
    volumes:
      - db:/var/lib/postgresql/data

  #  liquibase:
  #    image: liquibase/liquibase:4.17
  #    container_name: liquibase
  #    restart: no
  #    depends_on:
  #      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: nice@ass.com
      PGADMIN_DEFAULT_PASSWORD: nice
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
    networks:
      - main
    volumes:
      - pgadmin:/var/lib/pgadmin

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass qwe123qwe
    networks:
      - main
    volumes:
      - redis:/data

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    depends_on:
      - redis
    ports:
      - '6380:8001'
    networks:
      - main
    volumes:
      - redis_insight:/db


#  jenkins:
#    image: jenkins/jenkins:lts
#    ports:
#      - '8765:8765'
#    container_name: jenkins

networks:
  main:

volumes:
  db:
    driver: local
  redis:
    driver: local
  redis_insight:
    driver: local
  pgadmin:
    driver: local